config/routes.rb
require 'sidekiq/web'

SvnFilter::Application.routes.draw do
  resources :repos

  root :to => 'repos#index'
  mount Sidekiq::Web, at: "/sidekiq"

end

app/models/local_repo.rb
class LocalRepo < ActiveRecord::Base
  belongs_to :repo, inverse_of: :local
  validates :repo, presence: true
  validates :path, presence: true, uniqueness: true
  validates :status, presence: true, numericality: { only_integer: true }
  validate :parent_dir_exists, :parent_dir_is_writable
  validate :path_doesnt_exist, on: :create
  attr_accessible :path
  after_initialize :init
  before_update :check_path_change
  after_save :mirror_repo

  DEFAULT_BASE_PATH = File.expand_path('../../../data', __FILE__)
  STATUS_PENDING = 0
  STATUS_REPO_CREATED = 1
  STATUS_REPO_HOOKS_ADDED = 2
  STATUS_REPO_SYNC_INIT = 3
  STATUS_REPO_SYNCED = 4

  def local_repo_sync(one_step = false)
    stoploop = false
    until stoploop
      case status
      when STATUS_PENDING
        create_repo
      when STATUS_REPO_CREATED
        add_hooks
      when STATUS_REPO_HOOKS_ADDED
        svnsync_init
      when STATUS_REPO_SYNC_INIT, STATUS_REPO_SYNCED
        svnsync_sync        
      end
      stoploop = one_step || status < 0 || status == STATUS_REPO_SYNCED
    end
  end

  def parent_dir_exists
  	unless File.directory?(parent_dir(path))
      errors.add(:path, "must be in an existing directory")
    end
  end

  def parent_dir_is_writable
    path_parent = parent_dir(path)
    if File.directory?(path_parent) and !File.writable?(path_parent)
      errors.add(:path, "is not writable")
    end
  end

  def path_doesnt_exist
    if !path.nil? and File.writable?(parent_dir(path)) and File.exist?(path)
      errors.add(:path, "already exists")
    end
  end

private

  def create_repo
    if svnadmin_create(path)
      update_attribute(:status, STATUS_REPO_CREATED)
    else
      update_attribute(:status, -1)
    end
  end

  def add_hooks
    revprop_hook = File.join(path, 'hooks', 'pre-revprop-change')
    f = File.new(revprop_hook, File::CREAT|File::TRUNC|File::RDWR, 0755)
    f.write(<<-EOF
#!/bin/sh
USER="$3"
if [ "$USER" = "svnsync" ]; then exit 0; fi
echo "Only the svnsync user can change revprops" >&2
exit 1
    EOF
    )
    f.close
    update_attribute(:status, STATUS_REPO_HOOKS_ADDED)
  end

  def svnsync_init
    if svnsync('init', path, {remote: repo.full_url})
      update_attribute(:status, STATUS_REPO_SYNC_INIT)
    else
      update_attribute(:status, -1)
    end
  end

  def svnsync_sync
    if svnsync('synchronize', path)
      update_attribute(:status, STATUS_REPO_SYNCED)
    else
      update_attribute(:status, -1)
    end
  end

  def svnadmin_create(path_name)
    system("svnadmin create #{path_name}")
  end

  def svnsync(action, path_name, options = {})
    if action == "init"
      cmd = "svnsync init --username svnsync --non-interactive file://#{path_name} #{options[:remote]}"
    elsif action == "synchronize"
      cmd = "svnsync synchronize file://#{path_name}"
    end
    system(cmd)
  end
  
  def parent_dir(dir)
    File.expand_path('../', dir)
  end

  def init
    self.status ||= 0
  end

  def check_path_change
    if changed? and changes.include?("path")
      self.status = 0
    end
  end

  def mirror_repo
    if status == 0
      SvnsyncWorker.perform_async(id)
    end
  end

end

app/models/repo.rb
class Repo < ActiveRecord::Base
  has_one :local, class_name: "LocalRepo", inverse_of: :repo
  validates :url, presence: true
  validate :has_valid_protocol
  validates :name, presence: true, uniqueness: true, format: { with: /^[a-zA-Z0-9_-]*$/ }
  validates_associated :local
  attr_accessible :name, :protocol, :url, :local_attributes
  accepts_nested_attributes_for :local, allow_destroy: true

  VALID_PROTOCOLS = %w(svn http https svn+ssh)

  def to_param
    "#{id}-#{name}".parameterize
  end

  def has_local?
    !local.nil?
  end

  def full_url
    "#{protocol}://#{url}"
  end
  
  def has_valid_protocol
    unless VALID_PROTOCOLS.include?(protocol)
      errors.add(:protocol, "must be one of #{VALID_PROTOCOLS.join(', ')}")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  layout "front", only: [:index, :new, :edit]
  # GET /repos
  # GET /repos.json
  def index
    @repos = Repo.all
    @repo = Repo.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @repos }
    end
  end

  # GET /repos/1
  # GET /repos/1.json
  def show
    @repo = Repo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @repo }
    end
  end

  # GET /repos/new
  # GET /repos/new.json
  def new
    @repo = Repo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @repo }
    end
  end

  # GET /repos/1/edit
  def edit
    @repo = Repo.find(params[:id])
  end

  # POST /repos
  # POST /repos.json
  def create
    @repo = Repo.new(params[:repo])

    respond_to do |format|
      if @repo.save
        format.html { redirect_to @repo, notice: 'Repo was successfully created.' }
        format.json { render json: @repo, status: :created, location: @repo }
      else
        format.html { render action: "new", layout: "front" }
        format.json { render json: @repo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /repos/1
  # PUT /repos/1.json
  def update
    @repo = Repo.find(params[:id])

    respond_to do |format|
      if @repo.update_attributes(params[:repo])
        format.html { redirect_to @repo, notice: 'Repo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @repo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repos/1
  # DELETE /repos/1.json
  def destroy
    @repo = Repo.find(params[:id])
    @repo.destroy

    respond_to do |format|
      format.html { redirect_to repos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/repos_helper.rb
module ReposHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SvnFilter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/front.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SvnFilter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container-fluid">
		<%= yield %>
	</div>
</body>
</html>

app/views/repos/_form.html.erb
<%= form_for @repo, html: { class: "form-inline" } do |f| %>
  <% if @repo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repo.errors.count, "error") %> prohibited this repo from being saved:</h2>

      <ul>
      <% @repo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="repo-path width-80 margin-center field-dark">
      <div class="select-hide-arrow">
        <%= f.label :protocol %>
        <%= f.select :protocol, Repo::VALID_PROTOCOLS, {}, { class: 'auto-width' } %>
      </div>://<%= f.label :url %>
      <%= f.text_field :url, { placeholder: "Tester", style: "width: inherit;" } %>
    </div>
  </div>
  <div class="field">
    <div class="width-80 margin-center multi-fields">
      <div class="field-dark push-right right-field cbox-field" style="position: relative;">
        <%= label_tag 'has_local', "Mirror repo locally" %>
        <%= check_box_tag 'has_local', 1, @repo.has_local?, { data: {field: 'local_repo', prefix: 'repo_local_attributes_'}, class: 'toggle-nested' } %>
        <a href='#' class="icon-question-sign no-decorate help-tip" data-toggle="popover" data-title="Creating A Mirror" data-content="Working with remote repos can be slow. Select this box to create a local mirror, this will take longer to create but additional actions will be quicker."></a>
      </div>

      <div class="field-dark no-label left-field tbox-field" style="width: 55%">
        <%= f.label :name %>
        <%= f.text_field :name, { placeholder: "Name this connection" } %>
      </div>
    </div>
  </div>

  <fieldset id="local_repo">
    <%= f.fields_for :local do |builder| %>
      <%= render 'local_fields', f: builder %>
    <% end %>
  </fieldset>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script type="text/javascript">
  (function() {
    var local = "<%= escape_javascript(render 'local_fields', f: ActionView::Helpers::FormBuilder.new('repo[local_attributes]', LocalRepo.new, self, {}, proc {}))%>";

    $('#has_local').data('create', local);
  }).call(this);
</script>

app/views/repos/_local_fields.html.erb
<div class="field">
	<div class="width-80 margin-center field-dark">
    <%= f.label :path %>
    <%= f.text_field :path, { placeholder: "Local Save Path", style: "width: 90%" } %>
    <%= f.hidden_field :_destroy %>
  </div>
</div>

app/views/repos/edit.html.erb
<div class="row-fluid">
  <div class="span6 offset3 feature-box">
    <h3>Create a new svn connection</h3>

    <%= render 'form' %>

	<%= link_to 'Back', repos_path %>
  </div>
</div>

<h1>Editing repo</h1>

<%= link_to 'Show', @repo %> |
<%= link_to 'Back', repos_path %>

app/views/repos/index.html.erb
<div class="row-fluid">
  <div class="span6 offset3 feature-box">
    <h3 class="head-title">Create a new svn connection...</h3>

    <%= render 'form' %>

    <hr class="inset-dark" />

    <div class="row-fluid">
      <div class="span4 offset4">
        <div class="dark-list-field">
          <div class="nice-scroll">
            <ul>
            <% @repos.each do |repo| %>
              <li><%= link_to raw("#{repo.name}<i class='icon-circle-arrow-right'></i>"), repo %></li>
            <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <h3 class="foot-title">...or use a saved connection</h3>
  </div>
</div>

app/views/repos/new.html.erb
<div class="row-fluid">
  <div class="span6 offset3 feature-box">
    <h3>Create a new svn connection</h3>

    <%= render 'form' %>

	<%= link_to 'Back', repos_path %>
  </div>
</div>

app/views/repos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @repo.name %>
</p>

<p>
  <b>Protocol:</b>
  <%= @repo.protocol %>
</p>

<p>
  <b>Url:</b>
  <%= @repo.url %>
</p>


<%= link_to 'Edit', edit_repo_path(@repo) %> |
<%= link_to 'Back', repos_path %>